INSERT INTO Products (game, title, type, rarity, cost_price, selling_price, image_url) VALUES

#---[MTG Cards]---#
("Magic: The Gathering", "Blightsteel Colossus", "Artifact Creature", "Foil Full-Art", 82.40, 103.00, "static\images\products\blightsteel-colossus.jpg"),
("Magic: The Gathering", "Mox Opal", "Artifact", "Non-Foil", 240.00, 300.00, "static\images\products\mox-opal.jpg"),
("Magic: The Gathering", "Force of Will", "instant", "Non-Foil Retro Border", 80.00, 100.00, "static\images\products\force-of-will.jpg"),
("Magic: The Gathering", "Demonic Tutor", "Sorcery", "Non-Foil Mystical Archive (EN)", 88.00, 110.00, "static\images\products\demonic-tutor.jpg"),
("Magic: The Gathering", "Time Warp", "Sorcery", "Non-Foil Mystical Archive (JP)", 24.00, 30.00, "static\images\products\time-warp.jpg"),
("Magic: The Gathering", "Snapcaster Mage", "Creature", "Non-Foil", 18.40, 23.00, "static\images\products\snapcaster-mage.jpg"),
("Magic: The Gathering", "Minamo, School at Water's Edge", "Legendary Land", "Foil", 64.00, 80.00, "static\images\products\minamo-school-at-water-s-edge.jpg"),
("Magic: The Gathering", "Ephemerate", "Instant", "Etched Foil Mystical Archive (EN)", 19.20, 24.00, "static\images\products\ephemerate.jpg"),
("Magic: The Gathering", "Jace, the Mind Sculptor", "Legendary Planeswalker", "Non-Foil", 20.00, 25.00, "static\images\products\jace-the-mind-sculptor.jpg"),
("Magic: The Gathering", "Land Tax", "Enchantment", "Non-Foil", 33.60, 42.00, "static\images\products\land-tax.jpg"),

#---[YGO Cards]---#
("Yu-Gi-Oh!", "Firewall Dragon Singularity", "Link Monster", "Overframe Starlight Rare", 200, 240.00, "static\images\products\FirewallDragonSigularity_Overframe.png"),
("Yu-Gi-Oh!", "Fiendsmith's Lacrima", "Fusion Monster", "Starlight Rare", 40.00, 50.00, "static\images\products\FiendsmithsLacrima.png"),
("Yu-Gi-Oh!", "D/D/D Marksman King Tell", "XYZ Monster", "Starlight Rare", 8.00, 10.000, "static\images\products\DDDMarksmanKingTell.png"),
("Yu-Gi-Oh!", "Nightmare Apprentice", "Effect Monster", "Stamped Starlight Rare", 20.00, 25.00, "static\images\products\NightmareApprentice_Stamped.png"),
("Yu-Gi-Oh!", "Maxx 'C'", "Effect Monster", "Stamped Starlight Rare", 16.00, 20.00, "static\images\products\MaxxC_Stamped.png"),
("Yu-Gi-Oh!", "Stand Up Centur-Ion!", "Quickplay Spell", "StampedStarlight Rare", 20.00, 25.00, "static\images\products\StandUpCenturIon_Stamped.png"),
("Yu-Gi-Oh!", "Shining Sarcophagus", "Continuous Spell", "Starlight Rare", 6.40, 8.00, "static\images\products\ShiningSarcophagus.png"),
("Yu-Gi-Oh!", "Dominus Impulse", "Trap", "Platinum Secret Rare", 60.00, 75.00, "static\images\products\DominusImpulse.png"),
("Yu-Gi-Oh!", "Snake-Eyes Doomed Dragon", "Fusion Monster", "Platinum Secret Rare", 7.20, 9.00, "static\images\products\SnakeEyesDoomedDragon.png"),
("Yu-Gi-Oh!", "Number C104: Umbral Horror Masquerade", "XYZ Monster", "Platinum Secret Rare", 5.6, 7.00, "static\images\products\NumberC104UmbralHorrorMasquerade.png"),
("Yu-Gi-Oh!", "Raigeki", "Spell", "Platinum Secret Rare", 4.00, 5.00, "static\images\products\Raigeki.png"),
("Yu-Gi-Oh!", "The Winged Dragon of Ra", "Effect Monster", "Stamped Starlight Rare", 40.00, 50.00, "static\images\products\TheWingedDragonofRa_Stamped.png"),
("Yu-Gi-Oh!", "Scapegoat", "Quickplay Spell", "Stamped Ultra Rare", 2.40, 3.00, "static\images\products\Scapegoat_Stamped.png"),
("Yu-Gi-Oh!", "Solemn Judgment", "Counter Trap", "Stamped Ultra Rare", 1.60, 2.00, "static\images\products\SolemnJudgment_Stamped.png"),
("Yu-Gi-Oh!", "Platinum Gadget", "Link Monster", "Collector's Rare", 2.00, 2.50, "static\images\products\PlatinumGadget.png"),
("Yu-Gi-Oh!", "PSY-Framegear Gamma", "Effect Monster", "Collector's Rare", 8.80, 11.00, "static\images\products\PSYFramegearGamma.png"),
("Yu-Gi-Oh!", "Bystial Saronir", "Effect Monster", "Collector's Rare", 2.00, 2.50, "static\images\products\BystialSaronir.png"),
("Yu-Gi-Oh!", "Dragon's Rebirth", "Trap", "Collector's Rare", 1.60, 2.00, "static\images\products\DragonsRebirth.png"),
("Yu-Gi-Oh!", "Linguriboh", "Link Monster", "Ultimate Rare", 3.60, 4.50, "static\images\products\Linguriboh.png"),
("Yu-Gi-Oh!", "Lancea, Ancestral Dragon of the Ice Mountain", "Synchro Monster", "Ultimate Rare", 12.00, 15.00, "static\images\products\LanceaAncestralDragonoftheIceMountain.png"),
("Yu-Gi-Oh!", "Kashtira Fenrir", "Effect Monster", "Ultimate Rare", 12.00, 15.00, "static\images\products\KashtiraFenrir.png"),
("Yu-Gi-Oh!", "Paleozoic Opabinia", "XYZ Monster", "Prismatic Secret Rare", 1.60, 2.00, "static\images\products\PaleozoicOpabinia.png"),
("Yu-Gi-Oh!", "Chaos Angel", "Synchro Monster", "Prismatic Secret Rare", 32.00, 40.00, "static\images\products\ChaosAngel.png");